# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.1
_src_path: gh:WouterJTB/copier-autoupdate
project_description: Repo created with the copier-autoupdate template
project_name: Repo from copier-autoupdate
